---
- name: Slurm
  hosts: slurm
  become: true

  vars_files:
    - "vars/slurm.yml"

  pre_tasks:
    - name: Print Ansible info useful for development
      debug:
        msg:
          - "{{ ansible_distribution }} {{ ansible_distribution_version }}"

  roles:
    - zorlin.slurm
